#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FHSDKAndroidTest.Resource", IsApplication=true)]

namespace FHSDKAndroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FHXamarinAndroidSDK.Resource.Attribute.buttonSize = global::FHSDKAndroidTest.Resource.Attribute.buttonSize;
			global::FHXamarinAndroidSDK.Resource.Attribute.circleCrop = global::FHSDKAndroidTest.Resource.Attribute.circleCrop;
			global::FHXamarinAndroidSDK.Resource.Attribute.colorScheme = global::FHSDKAndroidTest.Resource.Attribute.colorScheme;
			global::FHXamarinAndroidSDK.Resource.Attribute.imageAspectRatio = global::FHSDKAndroidTest.Resource.Attribute.imageAspectRatio;
			global::FHXamarinAndroidSDK.Resource.Attribute.imageAspectRatioAdjust = global::FHSDKAndroidTest.Resource.Attribute.imageAspectRatioAdjust;
			global::FHXamarinAndroidSDK.Resource.Attribute.scopeUris = global::FHSDKAndroidTest.Resource.Attribute.scopeUris;
			global::FHXamarinAndroidSDK.Resource.Color.common_action_bar_splitter = global::FHSDKAndroidTest.Resource.Color.common_action_bar_splitter;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_dark = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_dark;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_dark_default = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_dark_default;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_dark_disabled = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_dark_focused = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_dark_pressed = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_light = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_light;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_light_default = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_light_default;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_light_disabled = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_light_focused = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_light_focused;
			global::FHXamarinAndroidSDK.Resource.Color.common_google_signin_btn_text_light_pressed = global::FHSDKAndroidTest.Resource.Color.common_google_signin_btn_text_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_dark = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_dark;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_dark_default = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_dark_default;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_dark_disabled = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_dark_focused = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_dark_pressed = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_light = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_light;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_light_default = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_light_default;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_light_disabled = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_light_focused = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_light_focused;
			global::FHXamarinAndroidSDK.Resource.Color.common_plus_signin_btn_text_light_pressed = global::FHSDKAndroidTest.Resource.Color.common_plus_signin_btn_text_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_full_open_on_phone = global::FHSDKAndroidTest.Resource.Drawable.common_full_open_on_phone;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_dark = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_dark;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_dark_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_dark_focused = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_dark_normal = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_dark_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_dark_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_light = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_light;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_light_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_light_focused = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_light_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_light_normal = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_light_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_icon_light_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_icon_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_dark = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_dark;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_dark_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_dark_focused = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_dark_normal = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_dark_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_dark_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_light = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_light;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_light_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_light_focused = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_light_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_light_normal = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_light_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_google_signin_btn_text_light_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_google_signin_btn_text_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_ic_googleplayservices = global::FHSDKAndroidTest.Resource.Drawable.common_ic_googleplayservices;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_dark = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_dark;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_dark_focused = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_dark_normal = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_dark_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_light = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_light;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_light_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_light_focused = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_light_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_light_normal = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_light_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_icon_light_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_icon_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_dark = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_dark;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_dark_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_dark_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_dark_focused = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_dark_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_dark_normal = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_dark_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_dark_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_dark_pressed;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_light = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_light;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_light_disabled = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_light_disabled;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_light_focused = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_light_focused;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_light_normal = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_light_normal;
			global::FHXamarinAndroidSDK.Resource.Drawable.common_plus_signin_btn_text_light_pressed = global::FHSDKAndroidTest.Resource.Drawable.common_plus_signin_btn_text_light_pressed;
			global::FHXamarinAndroidSDK.Resource.Id.adjust_height = global::FHSDKAndroidTest.Resource.Id.adjust_height;
			global::FHXamarinAndroidSDK.Resource.Id.adjust_width = global::FHSDKAndroidTest.Resource.Id.adjust_width;
			global::FHXamarinAndroidSDK.Resource.Id.auto = global::FHSDKAndroidTest.Resource.Id.auto;
			global::FHXamarinAndroidSDK.Resource.Id.dark = global::FHSDKAndroidTest.Resource.Id.dark;
			global::FHXamarinAndroidSDK.Resource.Id.icon_only = global::FHSDKAndroidTest.Resource.Id.icon_only;
			global::FHXamarinAndroidSDK.Resource.Id.light = global::FHSDKAndroidTest.Resource.Id.light;
			global::FHXamarinAndroidSDK.Resource.Id.none = global::FHSDKAndroidTest.Resource.Id.none;
			global::FHXamarinAndroidSDK.Resource.Id.standard = global::FHSDKAndroidTest.Resource.Id.standard;
			global::FHXamarinAndroidSDK.Resource.Id.wide = global::FHSDKAndroidTest.Resource.Id.wide;
			global::FHXamarinAndroidSDK.Resource.Integer.google_play_services_version = global::FHSDKAndroidTest.Resource.Integer.google_play_services_version;
			global::FHXamarinAndroidSDK.Resource.String.auth_google_play_services_client_facebook_display_name = global::FHSDKAndroidTest.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::FHXamarinAndroidSDK.Resource.String.auth_google_play_services_client_google_display_name = global::FHSDKAndroidTest.Resource.String.auth_google_play_services_client_google_display_name;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_api_unavailable_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_api_unavailable_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_enable_button = global::FHSDKAndroidTest.Resource.String.common_google_play_services_enable_button;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_enable_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_enable_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_enable_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_enable_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_install_button = global::FHSDKAndroidTest.Resource.String.common_google_play_services_install_button;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_install_text_phone = global::FHSDKAndroidTest.Resource.String.common_google_play_services_install_text_phone;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_install_text_tablet = global::FHSDKAndroidTest.Resource.String.common_google_play_services_install_text_tablet;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_install_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_install_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_invalid_account_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_invalid_account_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_invalid_account_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_invalid_account_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_network_error_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_network_error_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_network_error_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_network_error_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_notification_ticker = global::FHSDKAndroidTest.Resource.String.common_google_play_services_notification_ticker;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_restricted_profile_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_restricted_profile_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_restricted_profile_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_restricted_profile_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_sign_in_failed_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_sign_in_failed_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_sign_in_failed_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_sign_in_failed_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_unknown_issue = global::FHSDKAndroidTest.Resource.String.common_google_play_services_unknown_issue;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_unsupported_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_unsupported_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_unsupported_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_unsupported_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_update_button = global::FHSDKAndroidTest.Resource.String.common_google_play_services_update_button;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_update_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_update_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_update_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_update_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_updating_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_updating_text;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_updating_title = global::FHSDKAndroidTest.Resource.String.common_google_play_services_updating_title;
			global::FHXamarinAndroidSDK.Resource.String.common_google_play_services_wear_update_text = global::FHSDKAndroidTest.Resource.String.common_google_play_services_wear_update_text;
			global::FHXamarinAndroidSDK.Resource.String.common_open_on_phone = global::FHSDKAndroidTest.Resource.String.common_open_on_phone;
			global::FHXamarinAndroidSDK.Resource.String.common_signin_button_text = global::FHSDKAndroidTest.Resource.String.common_signin_button_text;
			global::FHXamarinAndroidSDK.Resource.String.common_signin_button_text_long = global::FHSDKAndroidTest.Resource.String.common_signin_button_text_long;
			global::FHXamarinAndroidSDK.Resource.String.library_name = global::FHSDKAndroidTest.Resource.String.library_name;
			global::FHXamarinAndroidSDK.Resource.Styleable.LoadingImageView = global::FHSDKAndroidTest.Resource.Styleable.LoadingImageView;
			global::FHXamarinAndroidSDK.Resource.Styleable.LoadingImageView_circleCrop = global::FHSDKAndroidTest.Resource.Styleable.LoadingImageView_circleCrop;
			global::FHXamarinAndroidSDK.Resource.Styleable.LoadingImageView_imageAspectRatio = global::FHSDKAndroidTest.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::FHXamarinAndroidSDK.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::FHSDKAndroidTest.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::FHXamarinAndroidSDK.Resource.Styleable.SignInButton = global::FHSDKAndroidTest.Resource.Styleable.SignInButton;
			global::FHXamarinAndroidSDK.Resource.Styleable.SignInButton_buttonSize = global::FHSDKAndroidTest.Resource.Styleable.SignInButton_buttonSize;
			global::FHXamarinAndroidSDK.Resource.Styleable.SignInButton_colorScheme = global::FHSDKAndroidTest.Resource.Styleable.SignInButton_colorScheme;
			global::FHXamarinAndroidSDK.Resource.Styleable.SignInButton_scopeUris = global::FHSDKAndroidTest.Resource.Styleable.SignInButton_scopeUris;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::FHSDKAndroidTest.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::FHSDKAndroidTest.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::FHSDKAndroidTest.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::FHSDKAndroidTest.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::FHSDKAndroidTest.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::FHSDKAndroidTest.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::FHSDKAndroidTest.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::FHSDKAndroidTest.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::FHSDKAndroidTest.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::FHSDKAndroidTest.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::FHSDKAndroidTest.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::FHSDKAndroidTest.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::FHSDKAndroidTest.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::FHSDKAndroidTest.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::FHSDKAndroidTest.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::FHSDKAndroidTest.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::FHSDKAndroidTest.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::FHSDKAndroidTest.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::FHSDKAndroidTest.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::FHSDKAndroidTest.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::FHSDKAndroidTest.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::FHSDKAndroidTest.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int OptionHostName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int OptionPort = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int OptionRemoteServer = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int OptionsButton = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int ResultFullName = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int ResultMessage = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int ResultResultState = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int ResultRunSingleMethodTest = 2131034122;
			
			// aapt resource value: 0x7f05000e
			public const int ResultStackTrace = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int ResultsFailed = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int ResultsId = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int ResultsIgnored = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ResultsInconclusive = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ResultsMessage = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int ResultsPassed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ResultsResult = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int RunTestsButton = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int TestSuiteListView = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
